version: '2.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-microcenter
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=4QADjDwZzo60YDpg
      - MYSQL_USER=microcenter
      - MYSQL_PASSWORD=2Pn36D3iM8vnTAul
      - MYSQL_DATABASE=microcenter
    labels:
      - traefik.enable = false
    networks:
      - microcenter
    volumes:
    - mysql:/var/lib/mysql
  splunk:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=J1T3bH8rVOd71ABt
      - SPLUNK_LICENSE_URI=Free
    ports:
      - 1921:8000
    networks:
      - microcenter
    labels:
      - traefik.enable = true
  selenium-microcenter:
    container_name: selenium-microcenter
    image:
      selenium/standalone-chrome:4.0
    ports:
    - 4444:4444
    volumes:
    - /dev/shm:/dev/shm
    networks:
      - microcenter
  microcenter-scraper-python:
    image:
      microcenter-scraper-python
    container_name: microcenter-scraper-python
    restart: unless-stopped
    networks:
      - microcenter
#  microcenter-discord-bot:
#    image:
#      microcenter-discord-bot
#    container_name: microcenter-discord-bot
#    restart: unless-stopped
#    environment:
#      DISCORD_TOKEN: 'REPLACE THIS WITH YOURS'
#    networks:
#      - microcenter
networks:
  microcenter:
    driver: bridge
volumes:
  mysql:
