version: '2.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-microcenter
    restart: unless-stopped
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=4QADjDwZzo60YDpg
      - MYSQL_USER=microcenter
      - MYSQL_PASSWORD=2Pn36D3iM8vnTAul
      - MYSQL_DATABASE=microcenter
    labels:
      - traefik.enable = false
    networks:
      - microcenter
  apache-superset:
    image: apache/incubator-superset
    ports:
    - 8090:8080
    container_name: microcenter-superset
    labels:
      - traefik.enable = true
      - traefik.docker.network = microcenter
    networks:
      - microcenter
  selenium-microcenter:
    container_name: selenium-microcenter
    image:
      selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201208
    ports:
    - 4444:4444
    volumes:
    - /dev/shm:/dev/shm
    networks:
      - microcenter
  microcenter-scraper-python:
    image:
      microcenter-scraper-python
    container_name: microcenter-scraper-python
    restart: unless-stopped
    networks:
      - microcenter

networks:
  microcenter:
    driver: bridge
