services:
  selenium-appname:
    container_name: selenium-appname
    image:
      selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201208
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - network-name
  java-app:
    image:
      java-app
    container_name: java-app
    restart: unless-stopped
    networks:
      - network-name
networks:
  network-name:
    driver: bridge