version: '2.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-microcenter
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=4QADjDwZzo60YDpg
      - MYSQL_USER=microcenter
      - MYSQL_PASSWORD=2Pn36D3iM8vnTAul
      - MYSQL_DATABASE=microcenter
    networks:
      - microcenter
    volumes:
      - mysql:/var/lib/mysql
  selenium-microcenter:
    container_name: selenium-microcenter
    image:
      selenium/standalone-chrome:4.0
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - microcenter
  microcenter-java:
    image: microcenter-java
    container_name: microcenter-java
    restart: unless-stopped
    networks:
      - microcenter
networks:
  microcenter:
    driver: bridge
volumes:
  mysql:
